### ISSUE TITLE
Presale option with allowlist

### ISSUE THREAD

**Issue by juliancwirko** [juliancwirko/elven-nft-minter-sc#1]
- minting enabled after public sale starts, allowlist has the priority

**Comment by tannerhallman** [comment]
Curious how you would give priority to an allowlist? Would it not just be based on the timing?

Or this proposal to create a whitelist period (the allowlist?)?

**Comment by juliancwirko** [comment]
My initial idea was to strictly integrate it with the 'drops' and add the allowlist of addresses when you want to create the drop. This way, you can make the first drop for only allow listed addresses. And then create more drops with standard rules. So basically, when the allowlist is defined, the current drop will only respect those. No other addresses will be able to mint. You, as an owner, will be responsible for correctly configuring the drop. It should correspond to the addresses added. But of course, this is just an initial idea. I need to check what will be the cleanest and simple solution.

**Comment by butavpaul** [comment]
Maybe, as an idea, you should also keep it in that way that you can create multiple drops (with multiple whitelists)
Pre-sale1, pre-sale 2 and so on or even full drop for the entire collection.

**Comment by juliancwirko** [comment]
Drops can be configured freely, even one for the whole collection. 

The only problem is that keeping many states active (like many allowlists active) will create edge cases where, for example, some of the addresses from the first allowlist won't buy the NFTs at all. And what to do with them? Also, maintaining all the states on the smart contract will introduce a lot of conditional logic.

I would keep it simple, and if the owner will unset the drop with the allowlist, then the allowlist is removed, and the owner can create the new one with a new drop, or the owner can create a standard drop without the allowlist. So the owner needs to think about how it will be planned before starting the smart contract.

**Comment by juliancwirko** [comment]
The final version lives on the development branch. It requires some more tests. Docs will be updated after that.

The logic:

1. It doesn't need a 'drops' setup, but still, it can be integrated with them. Both will work independently
2. The list can be populated by hand or through a JSON file with the array of addresses from sc/nft-minter dir
3. The operator can always add more addresses at any time, there is no way to duplicate them, so duplicated entries will be omitted. However, still, there is a limit check, 250 addresses per transaction. Duplications will be counted but not saved
4. For performance reasons, the list isn't cleared, but limits per drop and total limits are respected
5. There are new queries that allow checking if the address is on the list, how extensive is the list and if it is enabled or disabled
6. There are new endpoints for populating the allowlist, disabling it, and enabling it

**Comment by juliancwirko** [comment]
1.4.0

**Comment by butavpaul** [comment]
"The list can be populated by hand or through a JSON file with the array of addresses from sc/nft-minter dir"

What's the name I need to use for the whitelists in nft-minter? allowlist.json ?
